admin/src/web/__init__.py
from flask import Flask, redirect, render_template
from src.web.config import config
from src.web.controllers.category import category_blueprint
from src.web.controllers.frecuent_task import frecuent_task_blueprint
from src.web.controllers.regular_task import regular_task_blueprint
from src.models.db import db, init_db


def create_app(env="development", static_folder="static"):
    app = Flask(__name__, static_folder=static_folder)
    app.config.from_object(config[env])

    @app.get("/")
    def home():
        return redirect("/regular-tasks/")

    app.register_blueprint(category_blueprint)
    app.register_blueprint(frecuent_task_blueprint)
    app.register_blueprint(regular_task_blueprint)

    with app.app_context():
        init_db(app)

    @app.teardown_appcontext
    def shutdown_session(exception=None):
        db.session.remove()

    return app

admin/src/web/controllers/category.py
from flask import Blueprint, render_template, request, redirect
from src.models import category

category_blueprint = Blueprint("categories", __name__, url_prefix="/categories")


@category_blueprint.route("/create-category", methods=["GET", "POST"])
def create_category():
    if request.method == "GET":
        return render_template("/categories/add_category.html")
    data = {
        "name": request.form.get("name"),
        "description": request.form.get("description"),
        "icon": request.form.get("icon"),
        "color": request.form.get("color"),
    }
    category.create(data)
    return redirect("/categories/")


@category_blueprint.route("/category/<id>", methods=["GET", "POST"])
def update_category(id):
    if request.method == "GET":
        kwargs = {"category": category.find_by_id(id)}
        return render_template("/categories/show_category.html", **kwargs)
    data = {
        "id": request.form.get("id"),
        "name": request.form.get("name"),
        "description": request.form.get("description"),
        "icon": request.form.get("icon"),
        "color": request.form.get("color"),
    }
    category.update(data)
    return redirect("/categories/")


@category_blueprint.get("/")
def list_all():
    per_page = 10  # need this variable to be customizable eventually
    page = request.args.get("page", 1, type=int)
    kwargs = {"categories": category.list_categories(page=page, per_page=per_page)}
    return render_template("/categories/list_all.html", **kwargs)


@category_blueprint.route("/delete/<id>", methods=["GET", "DELETE"])
def delete_category(id):
    category.delete_by_id(id)
    return redirect("/categories/")

admin/src/web/controllers/frecuent_task.py
from flask import Blueprint, render_template, request, redirect, url_for
from src.models import frecuent_task
from src.models import category

frecuent_task_blueprint = Blueprint(
    "frecuent_tasks", __name__, url_prefix="/frecuent-tasks"
)


@frecuent_task_blueprint.route("/create-task", methods=["GET", "POST"])
def create_task():
    if request.method == "GET":
        return render_template(
            "/frecuent_tasks/add_task.html",
            categories=category.all_categories(),
        )
    data = {
        "name": request.form.get("name"),
        "description": request.form.get("description"),
        "priority": int(request.form.get("priority")),
        "category": category.find_by_id(request.form.get("category_id")),
        "frecuency": request.form.get("frecuency"),
    }
    frecuent_task.create(data)
    return redirect(url_for("frecuent_tasks.list_all", category=data["category"].name))


@frecuent_task_blueprint.route("/task/<id>", methods=["GET", "POST"])
def update_task(id):
    if request.method == "GET":
        kwargs = {
            "task": frecuent_task.find_by_id(id),
            "categories": category.all_categories(),
        }
        return render_template("/frecuent_tasks/show_task.html", **kwargs)
    data = {
        "id": request.form.get("id"),
        "name": request.form.get("name"),
        "description": request.form.get("description"),
        "priority": int(request.form.get("priority")),
        "category": category.find_by_id(request.form.get("category_id")),
        "frecuency": request.form.get("frecuency"),
        "completed_today": request.form.get("completedToday") == "yes",
    }
    frecuent_task.update(data)
    return redirect(url_for("frecuent_tasks.list_all", category=data["category"].name))


@frecuent_task_blueprint.get("/")
def list_all():
    per_page = 10  # need this variable to be customizable eventually
    category_arg = request.args.get("category", "Facultad", type=str)
    selected_category = category.find_by_name(category_arg)
    page = request.args.get("page", 1, type=int)
    kwargs = {
        "tasks": frecuent_task.list_tasks(
            category_id=selected_category.id, page=page, per_page=per_page
        ),
        "categories": category.all_categories(),
        "header": selected_category.name,
    }
    return render_template("/frecuent_tasks/list_all.html", **kwargs)


@frecuent_task_blueprint.route("/delete/<id>", methods=["GET", "DELETE"])
def delete_task(id):
    task = frecuent_task.find_by_id(id)
    category = task.category.name
    frecuent_task.delete_by_id(id)
    return redirect(url_for("frecuent_tasks.list_all", category=category))

admin/src/web/controllers/regular_task.py
from flask import Blueprint, render_template, request, redirect, url_for
from src.models import regular_task
from src.models import category
from datetime import date

regular_task_blueprint = Blueprint("regular_tasks", __name__, url_prefix="/regular-tasks")


@regular_task_blueprint.route("/create-task", methods=["GET", "POST"])
def create_task():
    if request.method == "GET":
        return render_template(
            "/regular_tasks/add_task.html", categories=category.all_categories()
        )
    data = {
        "name": request.form.get("name"),
        "description": request.form.get("description"),
        "priority": int(request.form.get("priority")),
        "category": category.find_by_id(request.form.get("category_id")),
        "deadline": request.form.get("deadline"),
    }
    if data["deadline"] == "":
        data["deadline"] = date.min
    regular_task.create(data)
    return redirect(url_for("regular_tasks.list_all", category=data["category"].name))


@regular_task_blueprint.route("/task/<id>", methods=["GET", "POST"])
def update_task(id):
    if request.method == "GET":
        kwargs = {
            "task": regular_task.find_by_id(id),
            "categories": category.all_categories(),
        }
        return render_template("/regular_tasks/show_task.html", **kwargs)
    data = {
        "id": request.form.get("id"),
        "name": request.form.get("name"),
        "description": request.form.get("description"),
        "priority": int(request.form.get("priority")),
        "category": category.find_by_id(request.form.get("category_id")),
        "deadline": request.form.get("deadline"),
        "is_completed": request.form.get("is_completed") == "yes",
    }
    regular_task.update(data)
    return redirect(url_for("regular_tasks.list_all", category=data["category"].name))


@regular_task_blueprint.get("/")
def list_all():
    per_page = 10  # need this variable to be customizable eventually
    category_arg = request.args.get("category", "Facultad", type=str)
    selected_category = category.find_by_name(category_arg)
    page = request.args.get("page", 1, type=int)
    kwargs = {
        "tasks": regular_task.list_tasks(
            category_id=selected_category.id, page=page, per_page=per_page
        ),
        "categories": category.all_categories(),
        "header": selected_category.name,
    }
    for task in kwargs["tasks"]:
        year = task.deadline.strftime("%Y")
        month = task.deadline.strftime("%m")
        day = task.deadline.strftime("%d")
        task.deadline = f"{day}/{month}/{year}"
    return render_template("/regular_tasks/list_all.html", **kwargs)


@regular_task_blueprint.route("/delete/<id>", methods=["GET", "DELETE"])
def delete_task(id):
    task = regular_task.find_by_id(id)
    category = task.category.name
    regular_task.delete_by_id(id)
    return redirect(url_for("regular_tasks.list_all", category=category))

admin/src/web/templates/categories/add_category.html
{% extends "layout.html" %} {% block title %} Add category {% endblock %} {% block head %} {{
super() }} {% endblock %} {% block content %} {% with messages = get_flashed_messages() %} {% if
messages %}
<ul class="flashes">
	{% for message in messages %}
	<div class="alert alert-warning" role="alert">
		<li>{{ message }}</li>
	</div>
	{% endfor %}
</ul>
{% endif %} {% endwith %}
<div class="card">
	<h5 class="card-header">Add category</h5>
	<div class="card-body">
		<form method="POST" action="{{ url_for('categories.create_category')}}">
			<div class="row mb-4">
				<div class="col">
					<div class="form-outline">
						<label class="form-label" for="name">Name </label>
						<input type="text" id="name" name="name" class="form-control" required />
					</div>
				</div>
				<div class="col">
					<div class="form-outline">
						<label class="form-label" for="description">Description</label>
						<input
							type="text"
							id="description"
							name="description"
							class="form-control"
							required
						/>
					</div>
				</div>
			</div>

			<!-- 			<div class="row mb-4">
				<div class="col">
					<div class="form-outline">
						<label class="form-label" for="icon">Icon</label>
						<input type="text" id="icon" name="icon" class="form-control" required />
					</div>
				</div>
				<div class="col">
					<div class="form-outline">
						<label class="form-label" for="color">Color</label>
						<input type="text" id="color" name="color" class="form-control" required />
					</div>
				</div>
			</div> -->
			<button type="submit" class="btn btn-primary btn-block mb-4">Submit</button>
		</form>
	</div>
</div>

{% endblock %}

admin/src/web/templates/categories/list_all.html
{% extends "layout.html" %} {% block title %} Categories {% endblock %} {% block head %} {{ super()
}} {% endblock %} {% block content %} {% with messages = get_flashed_messages() %} {% if messages %}
<ul class="flashes">
	{% for message in messages %}
	<div class="alert alert-warning" role="alert">
		<li>{{ message }}</li>
	</div>
	{% endfor %}
</ul>
{% endif %} {% endwith %}
<table class="data-table">
	<thead>
		<tr>
			<th>Icon</th>
			<th>Name</th>
			<th>Description</th>
			<th>Date added</th>
			<th>Modify</th>
		</tr>
	</thead>
	<tbody>
		{% for item in categories.items %}
		<tr>
			<td>{{item.icon}}</td>
			<td>{{item.name}}</td>
			<td>{{item.description}}</td>
			<td>{{item.date_added}}</td>
			<td><a href="{{ url_for('categories.update_category', id=item.id) }}">Modify</a></td>
		</tr>
		{% endfor %}
	</tbody>
</table>
<div class="pagination mt-3">
	<ul class="pagination">
		{% if categories.has_prev %}
		<li class="page-item">
			<a
				class="page-link"
				href="{{ url_for('categories.list_all', page=categories.prev_num) }}"
			>
				{{ '<<<' }}
			</a>
		</li>
		{% endif %} {% for number in categories.iter_pages() %} {% if categories.page != number %}
		<li class="page-item">
			<a class="page-link" href="{{ url_for('categories.list_all', page=number) }}">
				{{ number }}
			</a>
		</li>
		{% else %}
		<li class="page-item active">
			<span class="page-link">{{ number }}</span>
		</li>
		{% endif %} {% endfor %} {% if categories.has_next %}
		<li class="page-item">
			<a
				class="page-link"
				href="{{ url_for('categories.list_all', page=categories.next_num) }}"
			>
				{{ '>>>' }}
			</a>
		</li>
		{% endif %}
	</ul>
</div>
<a href="{{ url_for('categories.create_category') }}" class="btn btn-primary" role="button"
	>Add category</a
>

{% endblock %}

admin/src/web/templates/categories/show_category.html
{% extends "layout.html" %} {% block title %} Category {{category.id}} {% endblock %} {% block head
%} {{ super() }} {% endblock %} {% block content %} {% with messages = get_flashed_messages() %} {%
if messages %}
<ul class="flashes">
	{% for message in messages %}
	<div class="alert alert-warning" role="alert">
		<li>{{ message }}</li>
	</div>
	{% endfor %}
</ul>
{% endif %} {% endwith %}
<div class="card">
	<h5 class="card-header">Modify category</h5>
	<div class="card-body">
		<form method="POST" action="{{ url_for('categories.update_category', id=category.id)}}">
			<input type="text" id="id" name="id" value="{{category.id}}" hidden readonly />
			<div class="row mb-4">
				<div class="col">
					<div class="form-outline">
						<label class="form-label" for="name">Name</label>
						<input
							type="text"
							id="name"
							name="name"
							class="form-control"
							value="{{category.name}}"
						/>
					</div>
				</div>
			</div>

			<div class="row mb-4">
				<div class="col">
					<div class="form-outline">
						<label class="form-label" for="description">Description</label>
						<input
							type="text"
							id="description"
							name="description"
							class="form-control"
							value="{{category.description}}"
						/>
					</div>
				</div>
			</div>

			<button type="submit" class="btn btn-primary btn-block mb-4">Accept</button>
			<button
				type="button"
				class="btn btn-danger mb-4"
				data-bs-toggle="modal"
				data-bs-target="#eliminarModal"
			>
				Delete
			</button>
		</form>
	</div>
</div>

<div
	class="modal"
	tabindex="-1"
	id="eliminarModal"
	aria-labelledby="eliminarModal"
	aria-hidden="true"
>
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Delete category</h5>
				<button
					type="button"
					class="btn-close"
					data-bs-dismiss="modal"
					aria-label="Close"
				></button>
			</div>
			<div class="modal-body">
				<p>Are you sure?</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
				<a
					href="{{ url_for('categories.delete_category', id=category.id)}}"
					class="btn btn-primary"
					>Yes</a
				>
			</div>
		</div>
	</div>
</div>
{% endblock %}

admin/src/web/templates/frecuent_tasks/list_all.html
{% extends "layout.html" %} {% block title %} Frecuent tasks {% endblock %} {% block head %} {{
super() }} {% endblock %} {% block content %} {% with messages = get_flashed_messages() %} {% if
messages %}
<ul class="flashes">
	{% for message in messages %}
	<div class="alert alert-warning" role="alert">
		<li>{{ message }}</li>
	</div>
	{% endfor %}
</ul>
{% endif %} {% endwith %}
<div class="position-relative">
	<div class="btn-group">
		<button
			type="button"
			class="btn btn-primary dropdown-toggle"
			data-bs-toggle="dropdown"
			aria-expanded="false"
		>
			Select category
		</button>
		<ul class="dropdown-menu">
			{% for category in categories %}
			<li>
				<a
					class="dropdown-item"
					href="{{ url_for('frecuent_tasks.list_all', category=category.name) }}"
					>{{category.name}}</a
				>
			</li>
			{% endfor %}
		</ul>
	</div>
	<h1 class="position-absolute top-0 start-50 translate-middle-x">Category: {{header}}</h1>
</div>

<table class="data-table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Description</th>
			<th>Frecuency</th>
			<th>Priority</th>
			<th>Last completed</th>
			<th>Date added</th>
			<th>Modify</th>
		</tr>
	</thead>
	<tbody>
		{% for item in tasks.items %}
		<tr>
			<td>{{item.name}}</td>
			<td>{{item.description}}</td>
			<td>{{item.frecuency}}</td>
			<td>{{item.priority}}</td>
			<td>{{item.last_completed}}</td>
			<td>{{item.date_added}}</td>
			<td><a href="{{ url_for('frecuent_tasks.update_task', id=item.id) }}">Modify</a></td>
		</tr>
		{% endfor %}
	</tbody>
</table>
<div class="pagination mt-3">
	<ul class="pagination">
		{% if tasks.has_prev %}
		<li class="page-item">
			<a
				class="page-link"
				href="{{ url_for('frecuent_tasks.list_all', page=tasks.prev_num) }}"
			>
				{{ '<<<' }}
			</a>
		</li>
		{% endif %} {% for number in tasks.iter_pages() %} {% if tasks.page != number %}
		<li class="page-item">
			<a class="page-link" href="{{ url_for('frecuent_tasks.list_all', page=number) }}">
				{{ number }}
			</a>
		</li>
		{% else %}
		<li class="page-item active">
			<span class="page-link">{{ number }}</span>
		</li>
		{% endif %} {% endfor %} {% if tasks.has_next %}
		<li class="page-item">
			<a
				class="page-link"
				href="{{ url_for('frecuent_tasks.list_all', page=tasks.next_num) }}"
			>
				{{ '>>>' }}
			</a>
		</li>
		{% endif %}
	</ul>
</div>
<a href="{{ url_for('frecuent_tasks.create_task') }}" class="btn btn-primary" role="button"
	>Add frecuent task</a
>

{% endblock %}

admin/src/web/templates/frecuent_tasks/show_task.html
{% extends "layout.html" %} {% block title %} Frecuent task {{task.id}} {% endblock %} {% block head
%} {{ super() }} {% endblock %} {% block content %} {% with messages = get_flashed_messages() %} {%
if messages %}
<ul class="flashes">
	{% for message in messages %}
	<div class="alert alert-warning" role="alert">
		<li>{{ message }}</li>
	</div>
	{% endfor %}
</ul>
{% endif %} {% endwith %}
<div class="card">
	<h5 class="card-header">Modify frecuent task</h5>
	<div class="card-body">
		<form method="POST" action="{{ url_for('frecuent_tasks.update_task', id=task.id)}}">
			<input type="text" id="id" name="id" value="{{task.id}}" hidden readonly />
			<div class="row mb-4">
				<div class="col">
					<div class="form-outline">
						<label class="form-label" for="name">Name</label>
						<input
							type="text"
							id="name"
							name="name"
							class="form-control"
							value="{{task.name}}"
						/>
					</div>
				</div>
			</div>

			<div class="row mb-4">
				<div class="col">
					<div class="form-outline">
						<label class="form-label" for="description">Description</label>
						<input
							type="text"
							id="description"
							name="description"
							class="form-control"
							value="{{task.description}}"
						/>
					</div>
				</div>
			</div>
			<div class="row mb-4">
				<div class="col">
					<div class="form-outline">
						<label class="form-label" for="priority">Priority</label>
						<select
							class="form-control select-input"
							id="priority"
							name="priority"
							required
						>
							<option value="{{task.priority}}">{{task.priority}}</option>
							<option value="5">5</option>
							<option value="4">4</option>
							<option value="3">3</option>
							<option value="2">2</option>
							<option value="1">1</option>
						</select>
					</div>
				</div>
			</div>
			<div class="row mb-4">
				<div class="col">
					<div class="form-outline">
						<label class="form-label" for="category">Category</label>
						<select
							class="form-control select-input"
							id="category_id"
							name="category_id"
							value="{{task.category.id}}"
							required
						>
							{% for category in categories %} {% if category.id == task.category.id
							%}
							<option selected="{{category.id}}" value="{{category.id}}">
								{{category.name}}
							</option>
							{% else %}
							<option value="{{category.id}}">{{category.name}}</option>
							{% endif %} {% endfor %}
						</select>
					</div>
				</div>
			</div>
			<div class="row mb-4">
				<div class="col">
					<div class="form-outline">
						<label class="form-label" for="frecuency">Frecuency</label>
						<input
							type="text"
							id="frecuency"
							name="frecuency"
							class="form-control"
							value="{{task.frecuency}}"
							required
						/>
					</div>
				</div>
			</div>
			<div class="row mb-4">
				<div class="col">
					<div class="form-outline">
						<label class="form-label" for="completedToday">Completed today?</label>
						<select
							class="form-control select-input"
							id="completedToday"
							name="completedToday"
							required
						>
							<option value="yes">Yes</option>
							<option selected="no" value="no">No</option>
						</select>
					</div>
				</div>
			</div>
			<button type="submit" class="btn btn-primary btn-block mb-4">Accept</button>
			<button
				type="button"
				class="btn btn-danger mb-4"
				data-bs-toggle="modal"
				data-bs-target="#eliminarModal"
			>
				Delete
			</button>
		</form>
	</div>
</div>
<div
	class="modal"
	tabindex="-1"
	id="eliminarModal"
	aria-labelledby="eliminarModal"
	aria-hidden="true"
>
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Delete frecuent task</h5>
				<button
					type="button"
					class="btn-close"
					data-bs-dismiss="modal"
					aria-label="Close"
				></button>
			</div>
			<div class="modal-body">
				<p>Are you sure?</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
				<a
					href="{{ url_for('frecuent_tasks.delete_task', id=task.id)}}"
					class="btn btn-primary"
					>Yes</a
				>
			</div>
		</div>
	</div>
</div>
{% endblock %}

admin/src/web/templates/regular_tasks/list_all.html
{% extends "layout.html" %} {% block title %} Regular tasks {% endblock %} {% block head %} {{
super() }} {% endblock %} {% block content %} {% with messages = get_flashed_messages() %} {% if
messages %}
<ul class="flashes">
	{% for message in messages %}
	<div class="alert alert-warning" role="alert">
		<li>{{ message }}</li>
	</div>
	{% endfor %}
</ul>
{% endif %} {% endwith %}
<div class="position-relative">
	<div class="btn-group">
		<button
			type="button"
			class="btn btn-primary dropdown-toggle"
			data-bs-toggle="dropdown"
			aria-expanded="false"
		>
			Select category
		</button>
		<ul class="dropdown-menu">
			{% for category in categories %}
			<li>
				<a
					class="dropdown-item"
					href="{{ url_for('regular_tasks.list_all', category=category.name) }}"
					>{{category.name}}</a
				>
			</li>
			{% endfor %}
		</ul>
	</div>
	<h1 class="position-absolute top-0 start-50 translate-middle-x">Category: {{header}}</h1>
</div>
<table class="data-table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Description</th>
			<th>Deadline</th>
			<th>Priority</th>
			<th>Date added</th>
			<th>Modify</th>
		</tr>
	</thead>
	<tbody>
		{% for item in tasks.items %}
		<tr>
			<td>{{item.name}}</td>
			<td>{{item.description}}</td>
			<td>{{item.deadline}}</td>
			<td>{{item.priority}}</td>
			<td>{{item.date_added}}</td>
			<td><a href="{{ url_for('regular_tasks.update_task', id=item.id) }}">Modify</a></td>
		</tr>
		{% endfor %}
	</tbody>
</table>
<div class="pagination mt-3">
	<ul class="pagination">
		{% if tasks.has_prev %}
		<li class="page-item">
			<a
				class="page-link"
				href="{{ url_for('regular_tasks.list_all', page=tasks.prev_num) }}"
			>
				{{ '<<<' }}
			</a>
		</li>
		{% endif %} {% for number in tasks.iter_pages() %} {% if tasks.page != number %}
		<li class="page-item">
			<a class="page-link" href="{{ url_for('regular_tasks.list_all', page=number) }}">
				{{ number }}
			</a>
		</li>
		{% else %}
		<li class="page-item active">
			<span class="page-link">{{ number }}</span>
		</li>
		{% endif %} {% endfor %} {% if tasks.has_next %}
		<li class="page-item">
			<a
				class="page-link"
				href="{{ url_for('regular_tasks.list_all', page=tasks.next_num) }}"
			>
				{{ '>>>' }}
			</a>
		</li>
		{% endif %}
	</ul>
</div>
<a href="{{ url_for('regular_tasks.create_task') }}" class="btn btn-primary" role="button"
	>Add regular task</a
>
{% endblock %}

admin/src/web/templates/regular_tasks/show_task.html
{% extends "layout.html" %} {% block title %} Regular task {{task.id}} {% endblock %} {% block head
%} {{ super() }} {% endblock %} {% block content %} {% with messages = get_flashed_messages() %} {%
if messages %}
<ul class="flashes">
	{% for message in messages %}
	<div class="alert alert-warning" role="alert">
		<li>{{ message }}</li>
	</div>
	{% endfor %}
</ul>
{% endif %} {% endwith %}
<div class="card">
	<h5 class="card-header">Modify regular task</h5>
	<div class="card-body">
		<form method="POST" action="{{ url_for('regular_tasks.update_task', id=task.id)}}">
			<input type="text" id="id" name="id" value="{{task.id}}" hidden readonly />
			<div class="row mb-4">
				<div class="col">
					<div class="form-outline">
						<label class="form-label" for="name">Name</label>
						<input
							type="text"
							id="name"
							name="name"
							class="form-control"
							value="{{task.name}}"
						/>
					</div>
				</div>
			</div>

			<div class="row mb-4">
				<div class="col">
					<div class="form-outline">
						<label class="form-label" for="description">Description</label>
						<input
							type="text"
							id="description"
							name="description"
							class="form-control"
							value="{{task.description}}"
						/>
					</div>
				</div>
			</div>
			<div class="row mb-4">
				<div class="col">
					<div class="form-outline">
						<label class="form-label" for="priority">Priority</label>
						<select
							class="form-control select-input"
							id="priority"
							name="priority"
							required
						>
							<option value="{{task.priority}}">{{task.priority}}</option>
							<option value="5">5</option>
							<option value="4">4</option>
							<option value="3">3</option>
							<option value="2">2</option>
							<option value="1">1</option>
						</select>
					</div>
				</div>
			</div>
			<div class="row mb-4">
				<div class="col">
					<div class="form-outline">
						<label class="form-label" for="category">Category</label>
						<select
							class="form-control select-input"
							id="category_id"
							name="category_id"
							value="{{task.category.id}}"
							required
						>
							{% for category in categories %} {% if category.id == task.category.id
							%}
							<option selected="{{category.id}}" value="{{category.id}}">
								{{category.name}}
							</option>
							{% else %}
							<option value="{{category.id}}">{{category.name}}</option>
							{% endif %} {% endfor %}
						</select>
					</div>
				</div>
			</div>
			<div class="row mb-4">
				<div class="col">
					<div class="form-outline">
						<label class="form-label" for="deadline">Deadline</label>
						<input
							type="date"
							id="deadline"
							name="deadline"
							min="2023-03-01"
							max="2025-12-31"
							class="form-control"
							value="{{task.deadline}}"
							required
						/>
					</div>
				</div>
			</div>
			<div class="row mb-4">
				<div class="col">
					<div class="form-outline">
						<label class="form-label" for="is_completed">Completed?</label>
						<select
							class="form-control select-input"
							id="is_completed"
							name="is_completed"
							required
						>
							<option value="yes">Yes</option>
							<option selected="no" value="no">No</option>
						</select>
					</div>
				</div>
			</div>
			<button type="submit" class="btn btn-primary btn-block mb-4">Accept</button>
			<button
				type="button"
				class="btn btn-danger mb-4"
				data-bs-toggle="modal"
				data-bs-target="#eliminarModal"
			>
				Delete
			</button>
		</form>
	</div>
</div>
<div
	class="modal"
	tabindex="-1"
	id="eliminarModal"
	aria-labelledby="eliminarModal"
	aria-hidden="true"
>
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Delete regular task</h5>
				<button
					type="button"
					class="btn-close"
					data-bs-dismiss="modal"
					aria-label="Close"
				></button>
			</div>
			<div class="modal-body">
				<p>Are you sure?</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
				<a
					href="{{ url_for('regular_tasks.delete_task', id=task.id)}}"
					class="btn btn-primary"
					>Yes</a
				>
			</div>
		</div>
	</div>
</div>
{% endblock %}